# **05. Intro to SQL**

## **05.1. Empezando con SQL y Pandas**

### **05.1.1. Introducción y preparación del entorno**

Abre el archivo sql local y permite hacer preguntas a la base de datos, esta siguiente es para obtener todas las tablas dentro de la base de datos.

In [129]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

# Consultar el catálogo del sistema para listar las tablas
tablas = pd.read_sql_query(query, conexion)
display(tablas)

# Cerrar la conexión al terminar
conexion.close()

                     name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution

Sabiendo los nombres de las tablas que estan dentro de la base de datos, al esoger una con el siguiente código se muestran las cinco primeras filas de la base de datos.

Como se utiliza Pandas la sintaxis es la de esta libreria por lo tanto tiene los métodos de filtrado de esta libreria.

In [130]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT * 
FROM crime_scene_report 
LIMIT 10;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.head())

# Cerrar la conexión al terminar
conexion.close()

,date,type,description,city
0,20180115,robbery,A Man Dressed as Spider-Man Is on a Robbery Spree,NYC
1,20180115,murder,Life? Dont talk to me about life.,Albany
2,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
3,20180215,murder,REDACTED REDACTED REDACTED,SQL City
4,20180215,murder,Someone killed the guard! He took an arrow to ...,SQL City

In [131]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT * 
FROM crime_scene_report;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.shape)

# Cerrar la conexión al terminar
conexion.close()

(1228, 4)

### **05.1.2. Obtención del esquema de creación de la tabla**

In [133]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT sql
FROM sqlite_master
WHERE type='table'
AND name='crime_scene_report';
"""

db = pd.read_sql_query(query, conexion)

# Imprimir por pantalla con iloc[] todo el contenido de la celda sql
print(db["sql"].iloc[0])

# Cerrar la conexión al terminar
conexion.close()

CREATE TABLE crime_scene_report (
        date integer,
        type text,
        description text,
        city text
    )

## **05.2. SELECT, FROM & WHERE**

### **05.2.1. SELECT... FROM**
La consulta SQL más básica selecciona una sola columna de una sola tabla. Para ello, indica la columna que desees después de la palabra SELECT y, a continuación, indica la tabla después de la palabra FROM.

### **05.2.2. WHERE...**
La función WHERE dentro de SQL sirve para filtrar la la respuesta de la pregunta que le hacemos a la base de datos, de forma que nos devuelva menos datos.

In [135]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT *
FROM 'crime_scene_report'
WHERE type='murder';
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

,date,type,description,city
0,20180115,murder,Life? Dont talk to me about life.,Albany
1,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
2,20180215,murder,REDACTED REDACTED REDACTED,SQL City
3,20180215,murder,Someone killed the guard! He took an arrow to ...,SQL City
4,20170107,murder,‘It proves nothing of the sort!’ said Alice. ‘...,Memphis
5,20170108,murder,get” is the same thing as “I get what I like”!’\n,Round Lake Beach
6,20170108,murder,"HEARTHRUG,\n",Jacksonville
7,20170111,murder,\n,Springdale
8,20170121,murder,"her, to pass away the time.\n",Murfreesboro
9,20170122,murder,"came near her, she began, in a low, timid voic...",Temecula
10,20170124,murder,"about something, my dear, and that makes you f...",Santa Clarita

## **05.3. GROUP BY, HAVING & COUNT**

### **05.3.1. COUNT()**
`COUNT()` como su nombre indica sirve para contar cuantas veces aparece un valor en la vista de la base de datos, por ejemplo en el siguiente código se cuentan cuantas ciudades dentro de la tabla de ''crime_scene_report'' tienen el tipo de ''murder''.

In [136]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT COUNT(city)
FROM 'crime_scene_report'
WHERE type='murder';
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

   COUNT(city)
0          148

### **05.3.2. GROUP BY**
La instrucción GROUP BY toma el nombre de una o varias columnas y trata todas las filas que tengan el mismo valor en esa columna como un único grupo cuando se aplican funciones de agregación como COUNT().

In [137]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT city, COUNT(*) AS total_homicidios
FROM 'crime_scene_report'
WHERE type='murder'
GROUP BY city;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:,:])

# Cerrar la conexión al terminar
conexion.close()

             city  total_homicidios
0        Aberdeen                 2
1           Akron                 1
2          Albany                 1
3        Amarillo                 1
4         Antioch                 1
..            ...               ...
119    Wilmington                 1
120  Winter Haven                 2
121        Yakima                 1
122       Yonkers                 2
123    Youngstown                 1

[124 rows x 2 columns]

### **05.3.3. GROUP BY... HAVING**
La cláusula HAVING se utiliza junto con GROUP BY para ignorar los grupos que no cumplen determinados criterios.

In [138]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT city, COUNT(*) AS total_homicidios
FROM 'crime_scene_report'
WHERE type='murder'
GROUP BY city
HAVING COUNT(*) > 1;
"""

# Tambien se puede hacer asi
#query = """
#SELECT city, COUNT(*) AS total_homicidios
#FROM 'crime_scene_report'
#WHERE type='murder'
#GROUP BY city
#HAVING total_homicidios > 1;
#"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:,:])

# Cerrar la conexión al terminar
conexion.close()

                city  total_homicidios
0           Aberdeen                 2
1             Austin                 2
2        Bakersfield                 2
3            Bel Air                 2
4               Cary                 2
5         Charleston                 2
6          Fairfield                 2
7           Glendale                 2
8            Madison                 3
9            Memphis                 2
10            Norman                 2
11        North Port                 2
12         Oceanside                 2
13            Odessa                 2
14  Round Lake Beach                 2
15          SQL City                 3
16        Scottsdale                 2
17          Syracuse                 2
18        Vero Beach                 3
19      Winter Haven                 2
20           Yonkers                 2

## **05.4. ORDER BY**

In [139]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT *
FROM 'crime_scene_report'
ORDER BY date ASC;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:,:])

# Cerrar la conexión al terminar
conexion.close()

,date,type,description,city
0,20170101,fraud,forgotten to ask.’\n,Long Beach
1,20170101,fraud,Alice did not wish to offend the Dormouse agai...,Oceanside
2,20170101,theft,"‘Yes,’ said Alice, ‘we learned French and musi...",Chicago
3,20170101,smuggling,"‘Now tell me, Pat, what’s that in the window?’\n",Gilbert
4,20170101,assault,"twist it up into a sort of knot, and then keep...",Nashville
...,...,...,...,...
1223,20180430,robbery,‘And how did you manage on the twelfth?’ Alice...,Trenton
1224,20180430,bribery,\n,Garden Grove
1225,20180430,fraud,‘Why not?’ said the March Hare.\n,Houma
1226,20180430,assault,\n,Fontana
1227,20180501,assault,be NO mistake about it: it was neither more no...,Trenton

In [140]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("sql-murder-mystery.db")

# Realizar tu consulta SQL
query = """
SELECT *
FROM 'crime_scene_report'
ORDER BY date DESC;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:,:])

# Cerrar la conexión al terminar
conexion.close()

,date,type,description,city
0,20180501,assault,be NO mistake about it: it was neither more no...,Trenton
1,20180430,murder,‘But what am I to do?’ said Alice.\n,Spokane
2,20180430,robbery,‘And how did you manage on the twelfth?’ Alice...,Trenton
3,20180430,bribery,\n,Garden Grove
4,20180430,fraud,‘Why not?’ said the March Hare.\n,Houma
...,...,...,...,...
1223,20170101,fraud,forgotten to ask.’\n,Long Beach
1224,20170101,fraud,Alice did not wish to offend the Dormouse agai...,Oceanside
1225,20170101,theft,"‘Yes,’ said Alice, ‘we learned French and musi...",Chicago
1226,20170101,smuggling,"‘Now tell me, Pat, what’s that in the window?’\n",Gilbert
1227,20170101,assault,"twist it up into a sort of knot, and then keep...",Nashville

## **05.5. AS & WITH**

### **05.5.1. AS**
En un tutorial anterior aprendiste a utilizar ''AS'' para renombrar las columnas generadas por tus consultas, lo que también se conoce como ''alias''. Esto es similar a cómo Python utiliza ''as'' para crear alias al realizar importaciones como ''import pandas as pd'' o ''import seaborn as sns''.

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT City, COUNT(SupportRepId) AS TotalClientes
FROM 'Customer'
GROUP BY City
ORDER BY TotalClientes DESC;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

             City  TotalClientes
0       São Paulo              2
1          Prague              2
2           Paris              2
3   Mountain View              2
4          London              2
5          Berlin              2
6     Yellowknife              1
7        Winnipeg              1
8          Warsaw              1
9          Vienne              1
10      Vancouver              1

### **05.5.2. WITH... AS**
Por sí sola, la cláusula `AS` es una forma práctica de depurar los datos devueltos por la consulta. Resulta aún más potente cuando se combina con la cláusula `WITH` en lo que se denomina una ''expresión de tabla común''.

Una expresión de tabla común (o CTE) es una tabla temporal que se devuelve dentro de la consulta. Las CTE son útiles para dividir las consultas en fragmentos más legibles, y se pueden escribir consultas sobre ellas.

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
WITH Something AS
(
    SELECT City, COUNT(SupportRepId) AS TotalClientes
    FROM 'Customer'
    GROUP BY City
    ORDER BY TotalClientes DESC
)
SELECT totalClientes
FROM Something;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

    TotalClientes
0               2
1               2
2               2
3               2
4               2
5               2
6               1
7               1
8               1
9               1
10              1

## **05.6. Joining Data**

### **05.6.1. JOIN**

In [45]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT ar.Name, al.Title
FROM Artist AS ar
INNER JOIN Album AS al
ON ar.ArtistId = al.ArtistID;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

                    Name                                  Title
0                  AC/DC  For Those About To Rock We Salute You
1                 Accept                      Balls to the Wall
2                 Accept                      Restless and Wild
3                  AC/DC                      Let There Be Rock
4              Aerosmith                               Big Ones
5      Alanis Morissette                     Jagged Little Pill
6        Alice In Chains                               Facelift
7   Antônio Carlos Jobim                         Warner 25 Anos
8           Apocalyptica         Plays Metallica By Four Cellos
9             Audioslave                             Audioslave
10            Audioslave                           Out Of Exile