# **06.Advance SQL**

## **06.1. JOINs and UNIONs**

### **06.1.1. JOINs**


- `(INNER) JOIN`: Devuelve únicamente las filas que tienen valores coincidentes en ambas tablas.
- `LEFT (OUTER) JOIN`: Devuelve todas las filas de la tabla de la izquierda y solo las filas coincidentes de la tabla de la derecha.
- `RIGHT (OUTER) JOIN`: Devuelve todas las filas de la tabla de la derecha y solo las filas coincidentes de la tabla de la izquierda.
- `FULL (OUTER) JOIN`: Devuelve todas las filas cuando hay una coincidencia en la tabla de la izquierda o en la de la derecha.

![Imagen de los tipos de JOINs](./images/JOINsTypes.png)

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT ar.Name, al.Title
FROM Artist AS ar
INNER JOIN Album AS al
ON ar.ArtistId = al.ArtistID;
"""

db = pd.read_sql_query(query, conexion)

display(db.loc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

                    Name                                  Title
0                  AC/DC  For Those About To Rock We Salute You
1                 Accept                      Balls to the Wall
2                 Accept                      Restless and Wild
3                  AC/DC                      Let There Be Rock
4              Aerosmith                               Big Ones
5      Alanis Morissette                     Jagged Little Pill
6        Alice In Chains                               Facelift
7   Antônio Carlos Jobim                         Warner 25 Anos
8           Apocalyptica         Plays Metallica By Four Cellos
9             Audioslave                             Audioslave
10            Audioslave                           Out Of Exile

### **06.1.2. UNIONs**
El operador *UNION* se utiliza para combinar el conjunto de resultados de dos o más sentencias *SELECT*.

El operador *UNION* elimina automáticamente las filas duplicadas del conjunto de resultados.

Requisitos para el uso de *UNION*:
- Todas las sentencias *SELECT* incluidas en *UNION* deben tener el mismo número de columnas.
- Las columnas también deben tener tipos de datos similares.
- Las columnas de todas las sentencias *SELECT* deben aparecer en el mismo orden.

In [20]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT Composer FROM Track
UNION
SELECT Title FROM Album;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.iloc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

                                            Composer
0                                               None
1                             ...And Justice For All
2  20th Century Masters - The Millennium Collecti...
3                      A Copland Celebration, Vol. I
4                         A Matter of Life and Death
5                                    A Real Dead One
6                                    A Real Live One
7                                 A Soprano Inspired
8         A TempestadeTempestade Ou O Livro Dos Dias
9                                            A-Sides

##### **06.1.2.1. UNION ALL**
El operador *UNION* ALL se utiliza para combinar el conjunto de resultados de dos o más sentencias *SELECT*.

El operador *UNION* ALL incluye todas las filas de cada sentencia, incluidos los posibles duplicados.

Requisitos para *UNION* ALL:
- Todas las sentencias *SELECT* incluidas en *UNION* ALL deben tener el mismo número de columnas.
- Las columnas también deben tener tipos de datos similares.
- Las columnas de todas las sentencias *SELECT* deben estar, además, en el mismo orden.

In [21]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT Composer FROM Track
UNION ALL
SELECT Title FROM Album;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.iloc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

                                            Composer
0          Angus Young, Malcolm Young, Brian Johnson
1  U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...
2  F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...
3  F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...
4                         Deaffy & R.A. Smith-Diesel
5          Angus Young, Malcolm Young, Brian Johnson
6          Angus Young, Malcolm Young, Brian Johnson
7          Angus Young, Malcolm Young, Brian Johnson
8          Angus Young, Malcolm Young, Brian Johnson
9          Angus Young, Malcolm Young, Brian Johnson

## **06.2. Funciones analiticas**
A continuación se explciara como definir funciones analíticas, que también operan sobre un conjunto de filas. Sin embargo, a diferencia de las funciones de agregación, las funciones analíticas devuelven un valor (que puede ser diferente) para cada fila de la tabla original.

Las funciones analíticas nos permiten realizar cálculos complejos con una sintaxis relativamente sencilla. Por ejemplo, podemos calcular rápidamente medias móviles y totales acumulados, entre otras magnitudes.

### **06.2.1. Sintaxis**
Creación de una base de datos para usarla en este curso.

In [32]:
import pandas as pd
import sqlite3

# 1. Conectar a la base de datos de SQLite
conn = sqlite3.connect("baseDeDatosPrueba.db")
cursor = conn.cursor()

# 2. Ejecutar SQL para crear la tabla
cursor.execute("""
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER,
    date DATE,
    time INTEGER
);
""")

# 3. Ejecutar SQL para insertar los registros
cursor.execute("""
INSERT INTO usuarios (id, date, time) VALUES
    (1, '2019-07-05', 22),
    (1, '2019-04-15', 26),
    (2, '2019-02-06', 28),
    (1, '2019-01-02', 30),
    (2, '2019-08-30', 20),
    (2, '2019-03-09', 22);
""")

# Confirmar y guardar los cambios realizados
conn.commit()

# 4. Exportar toda la base de datos a un archivo ejecutable .sql
with open("mi_base_de_datos_dump.sql", "w", encoding="utf-8") as f:
    for linea in conn.iterdump():
        f.write(f"{linea}\n")

# 5. Consultar la base de datos mediante SQL y cargar el resultado en Pandas
query = "SELECT * FROM usuarios"
df = pd.read_sql_query(query, conn)

display(df)

# Cerrar la conexión
conn.close()

   id        date  time
0   1  2019-07-05    22
1   1  2019-04-15    26
2   2  2019-02-06    28
3   1  2019-01-02    30
4   2  2019-08-30    20
5   2  2019-03-09    22

# SCRATCH

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

# Consultar el catálogo del sistema para listar las tablas
tablas = pd.read_sql_query(query, conexion)
display(tablas)

# Cerrar la conexión al terminar
conexion.close()

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT * 
FROM Album;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.iloc[:,:])

# Cerrar la conexión al terminar
conexion.close()

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [ ]:
import sqlite3
import pandas as pd

# Conectar al archivo
conexion = sqlite3.connect("Chinook_Sqlite.sqlite")

# Realizar tu consulta SQL
query = """
SELECT * 
FROM Track;
"""

df = pd.read_sql_query(query, conexion)

# Mostrar las primeras filas
display(df.iloc[:10,:])

# Cerrar la conexión al terminar
conexion.close()

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99