# **07. Intro to Marchine Learning**

## **07.1. Como funcionan los modelos**
- **Arbol de decisiones**: Es un enfoque de aprendizaje supervisado que se utiliza en estadística, minería de datos y aprendizaje automático. En este formalismo, se utiliza un árbol de decisión de clasificación o regresión como modelo predictivo para extraer conclusiones sobre un conjunto de observaciones.
![Decision tree on machine learning](./images/decisionTreeOnMachineLearning.png)

### **07.1.2. Exploración basica de datos**

#### **07.1.2.1. Usando pandas**

In [2]:
import pandas as pd

- `pd.read_csv()`: permite leer un archivo para interpretarlo con pandas.
- `describe()`: Es un resumen de la estructura que se le ha pasado como argumento a este metodo, depende el tipo de variable que este almacenada en la columna cambia la representacion de los datos.

In [6]:
# save filepath to variable for easier access
melbourne_file_path = './melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path) 
# print a summary of the data in Melbourne data
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

## **07.2. Mi primer modelo de Machine Learning**

### **07.2.1. Seleccionar datos para el modelaje**
- `db.columns`: muestra solo las columnas.

In [10]:
import pandas as pd

melbourne_file_path = './melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

Se eliminan los valores nulos o que no se han introducido para poder entrenar el modelo.

In [13]:
# dropna drops missing values (think of na as "not available")
melbourne_data = melbourne_data.dropna(axis=0)

#### **07.2.1.1. Seleccionar un objetivo de prediccion**
Puedes extraer una variable mediante la notación de puntos. Esta única columna se almacena en una ''Series'', que, a grandes rasgos, es como un ''DataFrame'' con una sola columna de datos.

Utilizaremos la notación de puntos para seleccionar la columna que queremos predecir, lo que se denomina ''objetivo de predicción''. Por convención, el objetivo de predicción se denomina ''y''. Así pues, el código que necesitamos para guardar los precios de las viviendas en los datos de Melbourne es

In [14]:
y = melbourne_data.Price

### **07.2.2. Seleccionar ''caracteristicas''**
Las columnas que se introducen en nuestro modelo (y que posteriormente se utilizan para realizar predicciones) se denominan ''características''. En nuestro caso, serían las columnas utilizadas para determinar el precio de la vivienda. A veces, se utilizarán como características todas las columnas excepto la variable objetivo. Otras veces, será mejor utilizar menos características.

Por ahora, construiremos un modelo con solo unas pocas características. Más adelante verás cómo iterar y comparar modelos construidos con diferentes características.

Seleccionamos varias características indicando una lista de nombres de columnas entre corchetes. Cada elemento de esa lista debe ser una cadena de caracteres (entre comillas).

In [16]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

Por convención, estos datos se denominan *X.f*.

In [21]:
X = melbourne_data[melbourne_features]

Revisión antes de entrenar el modelo de los datos que se le van a introducir.

In [23]:
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

- `head()`: permite ver las cinco primeras filas del archivo csv.

In [24]:
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

### **07.2.3. Construir el modelo**
Se utilizara la biblioteca *scikit-learn* para crear tus modelos. Al programar, esta biblioteca se escribe como ''sklearn'', tal y como verás en el código de ejemplo. Scikit-learn es, sin duda, la biblioteca más popular para modelar los tipos de datos que suelen almacenarse en DataFrames.

Los pasos para crear y utilizar un modelo son los siguientes:

- *Definir*: ¿Qué tipo de modelo será? ¿Un árbol de decisión? ¿Algún otro tipo de modelo? También se especifican otros parámetros del tipo de modelo.
- *Ajuste*: Capturar patrones a partir de los datos proporcionados. Esta es la esencia del modelado.
- *Predicción*: Tal y como suena.
- *Evaluación*: Determinar la precisión de las predicciones del modelo.

A continuación se muestra un ejemplo de cómo definir un modelo de árbol de decisión con scikit-learn y ajustarlo con las características y la variable objetivo.

---

- *fit()*: Divide los datos de entrenamiento del modelo en dos.

In [26]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=1)

# Fit model
melbourne_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

Muchos modelos de aprendizaje automático admiten cierto grado de aleatoriedad en el entrenamiento del modelo. Al especificar un número para `random_state`, te aseguras de obtener los mismos resultados en cada ejecución. Esto se considera una buena práctica. Puedes utilizar cualquier número, y la calidad del modelo no dependerá de manera significativa del valor concreto que elijas.

Ahora disponemos de un modelo ajustado que podemos utilizar para realizar predicciones.

En la práctica, lo más habitual es realizar predicciones sobre las nuevas viviendas que salen al mercado, en lugar de sobre aquellas de las que ya disponemos de precios. No obstante, realizaremos predicciones para las primeras filas de los datos de entrenamiento con el fin de comprobar cómo funciona la función `predict`.

In [29]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))
#print(melbourne_model.predict(X))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

## **07.3. Validacion del modelo**

### **07.3.1. ¿Que es la validación de modelos**
Interesa evaluar casi todos los modelos que construyas. En la mayoría de las aplicaciones (aunque no en todas), la medida relevante de la calidad de un modelo es la precisión predictiva. En otras palabras, si las predicciones del modelo se acercarán a lo que ocurre realmente.

Muchas personas cometen un grave error al medir la precisión predictiva. Realizan predicciones con sus datos de entrenamiento y comparan esas predicciones con los valores objetivo de los propios datos de entrenamiento. Enseguida verás cuál es el problema de este enfoque y cómo resolverlo, pero primero pensemos en cómo lo haríamos.

En primer lugar, tendrías que resumir la calidad del modelo de una forma comprensible. Si comparas los valores predichos y reales de 10 000 viviendas, probablemente encontrarás una mezcla de predicciones acertadas y erróneas. Revisar una lista de 10 000 valores predichos y reales no tendría sentido. Necesitamos resumir esto en una única métrica.

Existen muchas métricas para resumir la calidad del modelo, pero empezaremos con una llamada ''error absoluto medio'' (también conocido como MAE). Analicemos esta métrica empezando por la última palabra: ''error''.

El error de predicción para cada vivienda es:

```
error = valor real − valor previsto
```

Así pues, si una vivienda cuesta `150 000 $` y has previsto que costaría `100 000 $`, el error es de `50 000 $`.

Con la métrica MAE, tomamos el valor absoluto de cada error. Esto convierte cada error en un número positivo. A continuación, calculamos la media de esos errores absolutos. Esta es nuestra medida de la calidad del modelo. En lenguaje sencillo, se puede expresar así:

```
De media, nuestras predicciones tienen un error de aproximadamente X.
```

Para calcular el MAE, primero necesitamos un modelo. Este se ha creado en una celda oculta más abajo, que puedes consultar haciendo clic en el botón de código.

In [31]:
from sklearn.metrics import mean_absolute_error

predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y, predicted_home_prices)

1115.7467183128902

### **07.3.2. El problema con los resultados de "In-Sample"**
La medida que acabamos de calcular puede denominarse ''puntuación dentro de la muestra''. Hemos utilizado una única ''muestra'' de viviendas tanto para construir el modelo como para evaluarlo. A continuación explicamos por qué esto es un problema.

Imagina que, en el amplio mercado inmobiliario, el color de la puerta no guarda relación alguna con el precio de la vivienda.

Sin embargo, en la muestra de datos que has utilizado para construir el modelo, todas las viviendas con puertas verdes eran muy caras. La función del modelo es encontrar patrones que predigan los precios de las viviendas, por lo que detectará este patrón y siempre predecirá precios elevados para las viviendas con puertas verdes.

Dado que este patrón se ha extraído de los datos de entrenamiento, el modelo parecerá preciso en dichos datos.

Pero si este patrón no se cumple cuando el modelo analiza datos nuevos, el modelo resultaría muy impreciso al aplicarlo en la práctica.

Dado que el valor práctico de los modelos radica en realizar predicciones sobre datos nuevos, medimos su rendimiento con datos que no se utilizaron para construir el modelo. La forma más sencilla de hacerlo es excluir algunos datos del proceso de construcción del modelo y, a continuación, utilizarlos para comprobar la precisión del modelo con datos que no ha visto antes. Estos datos se denominan datos de validación.

### **07.3.3. Como programarlo**
La biblioteca scikit-learn cuenta con una función llamada `train_test_split` que permite dividir los datos en dos partes. Utilizaremos una parte de esos datos como datos de entrenamiento para ajustar el modelo, y la otra parte como datos de validación para calcular el `mean_absolute_error`.

In [35]:
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)
# Define model
melbourne_model = DecisionTreeRegressor()
# Fit model
melbourne_model.fit(train_X, train_y)

# get predicted prices on validation data
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))
print("Exito!")

267580.8769098343
Exito!

Tu error absoluto medio para los datos de la muestra fue de unos 500 dólares. Fuera de la muestra, supera los 250 000 dólares.

Esta es la diferencia entre un modelo que es casi totalmente preciso y otro que resulta inutilizable para la mayoría de los fines prácticos. A modo de referencia, el valor medio de una vivienda en los datos de validación es de 1,1 millones de dólares. Por lo tanto, el error en los nuevos datos es aproximadamente una cuarta parte del valor medio de una vivienda.

Hay muchas formas de mejorar este modelo, como experimentar para encontrar mejores características o diferentes tipos de modelos.